spring:
  application:
    name: crud-service
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:~/test
    username: test
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
server:
  port: 8090